### ISSUE TITLE
failed to get pod from cache

### ISSUE THREAD

**Issue by CoolDarran** [tkestack/gpu-manager#53]
After upgrade gpu-manager, I get error like this and cannot assign pod to this node even with an empty card

```
I1203 10:05:06.880207   23804 util.go:178] Pod csi-rbdplugin-8njc7 in namespace rook-ceph does not Request for GPU resource
I1203 10:05:06.880227   23804 allocator.go:978] failed to get pod 7ceaa552-d951-484c-8fcc-54156720a6de from allocatedPod cache
I1203 10:05:06.880241   23804 allocator.go:223] failed to get ready annotations for pod 7ceaa552-d951-484c-8fcc-54156720a6de
I1203 10:05:06.880252   23804 allocator.go:978] failed to get pod a45b5bc6-1b87-47b2-90a9-7d0a89baba92 from allocatedPod cache
I1203 10:05:06.880260   23804 allocator.go:223] failed to get ready annotations for pod a45b5bc6-1b87-47b2-90a9-7d0a89baba92
I1203 10:05:06.880270   23804 allocator.go:978] failed to get pod 5c44bd31-a8f1-494a-abb9-c6fc727489c8 from allocatedPod cache
I1203 10:05:06.880282   23804 allocator.go:223] failed to get ready annotations for pod 5c44bd31-a8f1-494a-abb9-c6fc727489c8
I1203 10:05:06.880293   23804 allocator.go:978] failed to get pod 2071a0cb-083f-47fc-8017-bebae32bbd6c from allocatedPod cache
I1203 10:05:06.880301   23804 allocator.go:223] failed to get ready annotations for pod 2071a0cb-083f-47fc-8017-bebae32bbd6c
```

`nvidia-smi` output:

```
Thu Dec  3 18:06:05 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 26%   43C    P5    13W / 250W |   4454MiB / 11177MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 32%   57C    P2    62W / 250W |   4250MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
| 30%   54C    P2    76W / 250W |   8688MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:0A:00.0 Off |                  N/A |
| 23%   23C    P8     8W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     24453      C   python                                      4444MiB |
|    1     24923      C   python                                      4240MiB |
|    2      8403      C   python                                      4434MiB |
|    2     25238      C   python                                      4244MiB |
+-----------------------------------------------------------------------------+
```

**Comment by CoolDarran** [comment]
Another error occured

gpu-manager log:
```
I1203 12:36:57.498905   23804 vmemory.go:107] PreStartContainer request for vmemory
I1203 12:36:57.499314   23804 vcore.go:103] PreStartContainer request for vcore
I1203 12:36:57.499359   23804 allocator.go:784] get preStartContainer call from k8s, req: &PreStartContainerRequest{DevicesIDs:[tencent.com/vcuda-core-80 tencent.com/vcuda-core-114 tencent.com/vcuda-core-93 tencent.com/vcuda-core-59 tencent.com/vcuda-core-4 tencent.com/vcuda-core-233 tencent.com/vcuda-core-226 tencent.com/vcuda-core-315 tencent.com/vcuda-core-256 tencent.com/vcuda-core-232 tencent.com/vcuda-core-173 tencent.com/vcuda-core-288 tencent.com/vcuda-core-175 tencent.com/vcuda-core-143 tencent.com/vcuda-core-242 tencent.com/vcuda-core-36 tencent.com/vcuda-core-89 tencent.com/vcuda-core-38 tencent.com/vcuda-core-329 tencent.com/vcuda-core-312 tencent.com/vcuda-core-116 tencent.com/vcuda-core-146 tencent.com/vcuda-core-347 tencent.com/vcuda-core-316 tencent.com/vcuda-core-372 tencent.com/vcuda-core-103 tencent.com/vcuda-core-324 tencent.com/vcuda-core-383 tencent.com/vcuda-core-310 tencent.com/vcuda-core-144 tencent.com/vcuda-core-253 tencent.com/vcuda-core-203 tencent.com/vcuda-core-41 tencent.com/vcuda-core-110 tencent.com/vcuda-core-117 tencent.com/vcuda-core-390 tencent.com/vcuda-core-120 tencent.com/vcuda-core-33 tencent.com/vcuda-core-286 tencent.com/vcuda-core-259 tencent.com/vcuda-core-238 tencent.com/vcuda-core-227 tencent.com/vcuda-core-170 tencent.com/vcuda-core-49 tencent.com/vcuda-core-362 tencent.com/vcuda-core-258 tencent.com/vcuda-core-149 tencent.com/vcuda-core-122 tencent.com/vcuda-core-294 tencent.com/vcuda-core-239],}
I1203 12:36:57.499518   23804 util.go:130] Try v2 checkpoint data format
I1203 12:36:57.501000   23804 util.go:178] Pod gpu-feature-discovery-6l2bv in namespace node-feature-discovery does not Request for GPU resource
I1203 12:36:57.501020   23804 util.go:178] Pod gpu-manager-tke-xpwgv in namespace kube-system does not Request for GPU resource
I1203 12:36:57.501028   23804 util.go:178] Pod kube-flannel-jjpxn in namespace kube-system does not Request for GPU resource
I1203 12:36:57.501040   23804 util.go:178] Pod csi-rbdplugin-8njc7 in namespace rook-ceph does not Request for GPU resource
I1203 12:36:57.501053   23804 util.go:178] Pod dcgm-exporter-gq4kj in namespace dcgm-exporter does not Request for GPU resource
I1203 12:36:57.501062   23804 util.go:178] Pod cattle-node-agent-pt8mn in namespace cattle-system does not Request for GPU resource
I1203 12:36:57.501074   23804 util.go:178] Pod csi-cephfsplugin-g84wp in namespace rook-ceph does not Request for GPU resource
I1203 12:36:57.501085   23804 util.go:178] Pod nfd-worker-hq6jg in namespace node-feature-discovery does not Request for GPU resource
I1203 12:36:57.501092   23804 util.go:178] Pod metallb-speaker-44jcm in namespace metallb does not Request for GPU resource
I1203 12:36:57.501100   23804 util.go:178] Pod exporter-node-cluster-monitoring-hd8dg in namespace cattle-prometheus does not Request for GPU resource
I1203 12:36:57.501128   23804 manager.go:363] process 4edfcec3-7034-4916-a610-27862fac368b
I1203 12:36:57.501360   23804 manager.go:352] Start vDevice server for /etc/gpu-manager/vm/4edfcec3-7034-4916-a610-27862fac368b
I1203 12:36:57.506535   23804 util.go:188] Determine if the container engine-handler needs GPU resource
I1203 12:37:00.134935   23804 manager.go:369] UID: 4edfcec3-7034-4916-a610-27862fac368b, cont: 6a56e367a0ed1183c07a5bc2b86f03e7c164bed56ab3df0bea3d0806655faa30 want to registration
I1203 12:37:00.135077   23804 manager.go:455] Write /etc/gpu-manager/vm/4edfcec3-7034-4916-a610-27862fac368b/6a56e367a0ed1183c07a5bc2b86f03e7c164bed56ab3df0bea3d0806655faa30/pids.config
I1203 12:37:00.144037   23804 logs.go:79] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

application log:

```
F1203 12:42:03.648023      32 client.go:78] fail to get response from manager, error rpc error: code = Unknown desc = empty pids
/tmp/cuda-control/src/register.c:87 rpc client exit with 255
```

**Comment by mYmNeo** [comment]
What‘s the version changes between your upgrade?

**Comment by CoolDarran** [comment]
> What‘s the version changes between your upgrade?

upgrade 1.1.0 to 1.1.1

**Comment by mYmNeo** [comment]
What do you mean 'empty card'? If you mean pod without gpu card, it should never processed by gpu-manager

**Comment by CoolDarran** [comment]
> What do you mean 'empty card'? If you mean pod without gpu card, it should never processed by gpu-manager

`nvidia-smi` output shows that GPU 3 has sufficient resources and no pods assigned to this card

**Comment by mYmNeo** [comment]
We fix a bug when gpu-manager restart because of lost checkpoint file. Unfortunately, you have to rebuild your pod to recover the checkpoint file

**Comment by CoolDarran** [comment]
> We fix a bug when gpu-manager restart because of lost checkpoint file. Unfortunately, you have to rebuild your pod to recover the checkpoint file

OK, thx. I will try it.

**Comment by CoolDarran** [comment]
fixed with v1.0.4

**Comment by zxt620** [comment]
> fixed with v1.1.2

i  have the same problem. what that you mean is v1.1.2 fixed the problem?but why i upgrate to v1.1.4, the problem still occured.
